import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { render, screen, cleanup, fireEvent, waitFor } from "@testing-library/react";
import type { WorkflowSuggestion } from "@/types";
import { WORKFLOW_AI_ADJUDICATION_TIMEOUT_MS } from "@/lib/workflow-suggestion-constants";

// ---------------------------------------------------------------------------
// Mocks — server actions + the supabase browser client the panel self-fetches
// from. Mocks must be declared before the component import.
// ---------------------------------------------------------------------------

const keepWorkflowSuggestion = vi.fn();
const replaceWorkflowSuggestion = vi.fn();
const removeWorkflowSuggestion = vi.fn();
const listWorkflowTemplates = vi.fn();

vi.mock("@/actions/workflow-suggestions", () => ({
  keepWorkflowSuggestion: (...a: unknown[]) => keepWorkflowSuggestion(...a),
  replaceWorkflowSuggestion: (...a: unknown[]) => replaceWorkflowSuggestion(...a),
  removeWorkflowSuggestion: (...a: unknown[]) => removeWorkflowSuggestion(...a),
}));

vi.mock("@/actions/workflow-templates", () => ({
  listWorkflowTemplates: (...a: unknown[]) => listWorkflowTemplates(...a),
}));

vi.mock("sonner", () => ({
  toast: { success: vi.fn(), error: vi.fn() },
}));

// The single open-suggestion row the supabase query resolves to. Tests mutate
// this before render.
let suggestionRow: Record<string, unknown> | null = null;

vi.mock("@/lib/supabase/client", () => ({
  createClient: () => ({
    from: () => {
      const builder: Record<string, unknown> = {};
      for (const m of ["select", "eq", "order", "limit"]) {
        builder[m] = vi.fn(() => builder);
      }
      builder.maybeSingle = vi.fn(() =>
        Promise.resolve({ data: suggestionRow, error: null }),
      );
      return builder;
    },
    channel: () => {
      const ch: Record<string, unknown> = {};
      ch.on = vi.fn(() => ch);
      ch.subscribe = vi.fn(() => ch);
      ch.unsubscribe = vi.fn();
      return ch;
    },
  }),
}));

// Import after mocks are wired.
import { WorkflowSuggestionPanel, isAdjudicating } from "./workflow-suggestion-panel";

function makeRow(overrides: Partial<WorkflowSuggestion> = {}): Record<string, unknown> {
  return {
    id: "sug-1",
    task_id: "task-1",
    idea_id: "idea-1",
    suggested_template_id: "tmpl-labelled",
    recommended_template_id: "tmpl-ai",
    source: "ai",
    reason: "Template looks like discovery, but this task is build work.",
    adjudication_started_at: null,
    status: "suggested",
    ...overrides,
  };
}

function tmpl(
  id: string,
  name: string,
  steps: number | Array<{ title?: string; role?: string }> = 1,
) {
  const arr =
    typeof steps === "number"
      ? Array.from({ length: steps }, () => ({}))
      : steps;
  return { id, name, steps: arr };
}

describe("WorkflowSuggestionPanel", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    suggestionRow = makeRow();
    listWorkflowTemplates.mockResolvedValue([]);
  });

  afterEach(() => cleanup());

  it("renders the suggested-mismatch heading, reason, and AI provenance badge", async () => {
    render(<WorkflowSuggestionPanel taskId="task-1" ideaId="idea-1" />);

    expect(
      await screen.findByText(/Suggested workflow looks mismatched/i),
    ).toBeInTheDocument();
    expect(
      screen.getByText(/this task is build work/i),
    ).toBeInTheDocument();
    // AI provenance badge (source === "ai").
    expect(screen.getByTitle(/generated by AI adjudication/i)).toBeInTheDocument();
  });

  it("renders the Rules provenance badge when source is heuristic", async () => {
    suggestionRow = makeRow({ source: "heuristic" });
    render(<WorkflowSuggestionPanel taskId="task-1" ideaId="idea-1" />);

    expect(await screen.findByTitle(/keyword heuristic/i)).toBeInTheDocument();
    expect(screen.queryByTitle(/AI adjudication/i)).not.toBeInTheDocument();
  });

  it("renders nothing when read-only", async () => {
    const { container } = render(
      <WorkflowSuggestionPanel taskId="task-1" ideaId="idea-1" isReadOnly />,
    );
    // Self-fetch resolves to a row, but read-only suppresses the panel.
    await waitFor(() => expect(container).toBeEmptyDOMElement());
  });

  it("Keep calls keepWorkflowSuggestion then onResolved", async () => {
    keepWorkflowSuggestion.mockResolvedValue({ ok: true });
    const onResolved = vi.fn();

    render(
      <WorkflowSuggestionPanel taskId="task-1" ideaId="idea-1" onResolved={onResolved} />,
    );

    fireEvent.click(await screen.findByRole("button", { name: /Keep & attach/i }));
    expect(keepWorkflowSuggestion).toHaveBeenCalledWith("sug-1");
    await waitFor(() => expect(onResolved).toHaveBeenCalled());
  });

  it("Remove calls removeWorkflowSuggestion then onResolved", async () => {
    removeWorkflowSuggestion.mockResolvedValue({ ok: true });
    const onResolved = vi.fn();

    render(
      <WorkflowSuggestionPanel taskId="task-1" ideaId="idea-1" onResolved={onResolved} />,
    );

    fireEvent.click(await screen.findByRole("button", { name: /Remove/i }));
    expect(removeWorkflowSuggestion).toHaveBeenCalledWith("sug-1");
    await waitFor(() => expect(onResolved).toHaveBeenCalled());
  });

  it("Replace picker orders AI-recommended first and originally-labelled last", async () => {
    listWorkflowTemplates.mockResolvedValue([
      tmpl("tmpl-labelled", "Labelled Discovery"),
      tmpl("tmpl-other", "Some Other"),
      tmpl("tmpl-ai", "AI Build Flow"),
    ]);

    render(<WorkflowSuggestionPanel taskId="task-1" ideaId="idea-1" />);
    fireEvent.click(await screen.findByRole("button", { name: /Replace/i }));

    const options = await screen.findAllByRole("option");
    const names = options.map((o) => o.textContent ?? "");
    // AI-recommended first, originally-labelled last.
    expect(names[0]).toContain("AI Build Flow");
    expect(names[0]).toMatch(/AI recommends/i);
    expect(names[names.length - 1]).toContain("Labelled Discovery");
    expect(names[names.length - 1]).toMatch(/originally labelled/i);
  });

  it("Replace picker auto-expands the AI-recommended steps and toggles others on demand", async () => {
    listWorkflowTemplates.mockResolvedValue([
      tmpl("tmpl-labelled", "Labelled Discovery", [
        { title: "Competitor analysis", role: "Analyst" },
      ]),
      tmpl("tmpl-ai", "AI Build Flow", [
        { title: "Requirements", role: "PO" },
        { title: "Implementation", role: "Engineer" },
      ]),
    ]);

    render(<WorkflowSuggestionPanel taskId="task-1" ideaId="idea-1" />);
    fireEvent.click(await screen.findByRole("button", { name: /Replace/i }));

    // Recommended template's steps are visible by default (no extra tap).
    expect(await screen.findByText("Implementation")).toBeInTheDocument();
    expect(screen.getByText("Requirements")).toBeInTheDocument();

    // Another template's steps stay hidden until its arrow is tapped.
    expect(screen.queryByText("Competitor analysis")).not.toBeInTheDocument();
    fireEvent.click(
      screen.getByRole("button", { name: /Show Labelled Discovery steps/i }),
    );
    expect(await screen.findByText("Competitor analysis")).toBeInTheDocument();
  });

  it("Replace picker shows the create-template hint when only the labelled template exists", async () => {
    listWorkflowTemplates.mockResolvedValue([tmpl("tmpl-labelled", "Labelled Only")]);

    render(<WorkflowSuggestionPanel taskId="task-1" ideaId="idea-1" />);
    fireEvent.click(await screen.findByRole("button", { name: /Replace/i }));

    expect(
      await screen.findByText(/only the labelled template/i),
    ).toBeInTheDocument();
    expect(
      screen.getByRole("link", { name: /Create a workflow template/i }),
    ).toBeInTheDocument();
  });

  it('renders the "checking fit…" state while adjudication is fresh and in flight', async () => {
    suggestionRow = makeRow({
      reason: null,
      adjudication_started_at: new Date().toISOString(),
    });
    render(<WorkflowSuggestionPanel taskId="task-1" ideaId="idea-1" />);

    expect(await screen.findByText(/Checking workflow fit/i)).toBeInTheDocument();
    expect(
      screen.queryByText(/Suggested workflow looks mismatched/i),
    ).not.toBeInTheDocument();
  });
});

describe("isAdjudicating", () => {
  it("is false once a reason is finalised, even with a fresh marker", () => {
    expect(
      isAdjudicating({
        reason: "done",
        adjudication_started_at: new Date().toISOString(),
      }),
    ).toBe(false);
  });

  it("is false with no adjudication marker", () => {
    expect(isAdjudicating({ reason: null, adjudication_started_at: null })).toBe(false);
  });

  it("is true within the shared adjudication window, false once stale", () => {
    const fresh = new Date(Date.now() - 1_000).toISOString();
    const stale = new Date(
      Date.now() - WORKFLOW_AI_ADJUDICATION_TIMEOUT_MS - 1_000,
    ).toISOString();
    expect(isAdjudicating({ reason: null, adjudication_started_at: fresh })).toBe(true);
    expect(isAdjudicating({ reason: null, adjudication_started_at: stale })).toBe(false);
  });
});
